FROM 335596040822.dkr.ecr.us-east-1.amazonaws.com/wolof-asr-fargate:latest

RUN pip install --no-cache-dir ctranslate2 sentencepiece

RUN mkdir -p /opt/nllb && \
    curl -sL -o /opt/nllb/model.bin https://huggingface.co/JustFrederik/nllb-200-distilled-600M-ct2-int8/resolve/main/model.bin && \
    curl -sL -o /opt/nllb/shared_vocabulary.json https://huggingface.co/JustFrederik/nllb-200-distilled-600M-ct2-int8/resolve/main/shared_vocabulary.json && \
    curl -sL -o /opt/nllb/config.json https://huggingface.co/JustFrederik/nllb-200-distilled-600M-ct2-int8/resolve/main/config.json && \
    curl -sL -o /opt/nllb/sentencepiece.bpe.model https://huggingface.co/facebook/nllb-200-distilled-600M/resolve/main/sentencepiece.bpe.model

COPY app.py /app/app.py

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--timeout", "300", "--workers", "1", "app:app"]
